/**
 * Premium Destiny Report — long-running background generator.
 *
 * Trigger: POST /.netlify/functions/premium-generate-background
 *   body: { orderId: string }
 *
 * Runs up to 15 min. Generates the Claude reading (~3-4 min with adaptive
 * thinking) in parallel with portrait path resolution, persists to Blobs,
 * and sends the delivery email via Resend.
 */

import Stripe from "stripe";
import { getOrder, updateOrder } from "../../lib/premiumOrder";
import { calculateBaZi } from "../../lib/bazi";
import { generatePremiumReading } from "../../lib/premiumReading";
import { sendPremiumReadyEmail } from "../../lib/premiumEmail";

/**
 * Refund the order via Stripe. Best-effort: returns true on success, false
 * otherwise (logged but not thrown).
 */
async function refundOrder(orderId: string): Promise<boolean> {
  const secret = process.env.STRIPE_SECRET_KEY;
  if (!secret) return false;
  try {
    const stripe = new Stripe(secret);
    // Get the payment_intent for this checkout session, then refund it.
    const session = await stripe.checkout.sessions.retrieve(orderId);
    const pi = typeof session.payment_intent === "string"
      ? session.payment_intent
      : session.payment_intent?.id;
    if (!pi) return false;
    await stripe.refunds.create({ payment_intent: pi, reason: "requested_by_customer" });
    return true;
  } catch (err) {
    console.error("Refund failed:", err);
    return false;
  }
}

export default async (req: Request) => {
  const { orderId } = (await req.json()) as { orderId: string };
  if (!orderId) {
    return new Response("Missing orderId", { status: 400 });
  }

  const order = await getOrder(orderId);
  if (!order) {
    return new Response("Order not found", { status: 404 });
  }

  if (order.status !== "paid") {
    return new Response(
      `Order status is ${order.status}, expected "paid"`,
      { status: 409 },
    );
  }

  await updateOrder(orderId, { status: "generating" });

  try {
    const chart = calculateBaZi(order.chartInput);

    // Reading + portrait path resolution run in parallel. Portrait files are
    // pre-generated by scripts/generate-awakened-portraits.ts, so we just
    // confirm the path. (Could add an exists-check via fetch here.)
    const awakenedPortraitPath = `/portraits/${order.daySlug}-${order.gender}-awakened.jpeg`;

    const reading = await generatePremiumReading(chart, order.name);

    const origin = new URL(req.url).origin;
    const emailRes = await sendPremiumReadyEmail(
      {
        ...order,
        reading,
        awakenedPortraitPath,
      },
      origin,
    );

    await updateOrder(orderId, {
      status: "done",
      reading,
      awakenedPortraitPath,
      emailSent: emailRes.ok,
      errorMessage: emailRes.ok ? undefined : `Email send failed: ${emailRes.error}`,
    });

    return new Response("", { status: 200 });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Generation failed";
    const refunded = await refundOrder(orderId);
    await updateOrder(orderId, {
      status: "error",
      errorMessage: refunded
        ? `${message} — your $9.9 has been automatically refunded`
        : `${message} — automatic refund failed; please contact hello@fivebazi.com`,
    });
    return new Response("", { status: 500 });
  }
};
