import type { Article } from "./types";
import { KEYWORDS } from "./_keywords";

export type { Article, ArticleCategory, ArticleSection, ArticleFAQ, InternalLinkRef } from "./types";
export { KEYWORDS } from "./_keywords";

// === BEGIN_GENERATED_IMPORTS ===
// (Generated by scripts/generate-articles.ts — do not edit by hand.)
import { article as a0 } from "./entries/what-is-bazi";
import { article as a1 } from "./entries/how-to-read-a-bazi-chart";
import { article as a2 } from "./entries/bazi-vs-western-astrology";
import { article as a3 } from "./entries/solar-vs-lunar-calendar-bazi";
import { article as a4 } from "./entries/free-bazi-vs-paid-reading";
import { article as a5 } from "./entries/what-is-day-master";
import { article as a6 } from "./entries/yang-wood-day-master";
import { article as a7 } from "./entries/yin-fire-day-master";
import { article as a8 } from "./entries/strong-vs-weak-day-master";
import { article as a9 } from "./entries/day-master-element-balance";
import { article as a10 } from "./entries/five-elements-explained";
import { article as a11 } from "./entries/too-much-fire-bazi";
import { article as a12 } from "./entries/missing-element-bazi";
import { article as a13 } from "./entries/generative-controlling-cycle";
import { article as a14 } from "./entries/dominant-element-bazi";
import { article as a15 } from "./entries/chinese-zodiac-compatibility";
import { article as a16 } from "./entries/best-zodiac-matches";
import { article as a17 } from "./entries/zodiac-year-boundary";
import { article as a18 } from "./entries/bazi-career-pillar";
import { article as a19 } from "./entries/bazi-relationship-pillar";
const GENERATED_ARTICLES: Article[] = [a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19];
// === END_GENERATED_IMPORTS ===

const ARTICLES_BY_SLUG: Record<string, Article> = Object.fromEntries(
  GENERATED_ARTICLES.map((a) => [a.slug, a])
);

export const ARTICLES = ARTICLES_BY_SLUG;

export const ARTICLE_LIST: Article[] = KEYWORDS
  .map((kw) => ARTICLES_BY_SLUG[kw.slug])
  .filter((a): a is Article => Boolean(a));

export const CATEGORY_LABELS: Record<Article["category"], string> = {
  fundamentals: "Fundamentals",
  "day-master": "Day Master",
  elements: "Five Elements",
  zodiac: "Zodiac",
};

export function articleHref(slug: string): string {
  return `/learn/${slug}`;
}
