// Generated by scripts/generate-articles.ts — do not edit by hand.
import type { Article } from "../types";

export const article: Article = {
  "slug": "chinese-zodiac-compatibility",
  "title": "Chinese Zodiac Compatibility: The Real Chart (Not Pop Horoscopes)",
  "metaDescription": "Real Chinese zodiac compatibility comes from the Three Harmonies and Six Clashes — not generic 'rats love dragons' lists. Here's the full picture, properly explained.",
  "h1": "Chinese Zodiac Compatibility — The Real Chart, Not the Pop Version",
  "category": "zodiac",
  "primaryKeyword": "chinese zodiac compatibility",
  "tldr": "Chinese zodiac compatibility is built on two classical frameworks: the Three Harmonies (sān hé 三合), which group animals that naturally support each other, and the Six Clashes (liù chōng 六冲), which pair animals whose energies create friction. Your year animal is just a starting point — a complete BaZi chart looks at four pillars, not one.",
  "intro": [
    "Most online compatibility charts reduce Chinese astrology to a single sentence: 'Rats love Dragons, avoid Horses.' That is not wrong exactly — but it is about 10% of the picture. The classical system behind Chinese zodiac compatibility is far more structured, and far more useful, than a color-coded grid.",
    "The real framework comes from two ancient groupings embedded in Chinese metaphysics. The Three Harmonies (sān hé 三合) identify animals that share an elemental resonance and strengthen each other. The Six Clashes (liù chōng 六冲) identify pairs whose energies oppose each other in ways that create real friction — not doom, but effort. Knowing which camp your pairing falls into changes how you read a relationship.",
    "One more caveat before diving in: the zodiac animal most people know is their birth year animal. In BaZi (Four Pillars of Destiny, bā zì 八字), the year pillar represents your social mask and early environment — not your core self. The Day Pillar (rì zhù 日柱), specifically the Day Master (rì zhǔ 日主), is far more important for romantic and close-partnership compatibility. Use the year animal as a quick lens, not a verdict."
  ],
  "sections": [
    {
      "h2": "How the Twelve Animals Are Actually Organized",
      "paragraphs": [
        "The twelve zodiac animals are not random — they map onto the twelve Earthly Branches (dì zhī 地支), each of which carries a specific elemental and directional energy. Four groups of three animals share a common element at the peak of their season. This is the foundation of the Three Harmonies. Separately, six pairs sit directly opposite each other on the zodiac wheel — 180 degrees apart — and these are the Six Clashes. Understanding the geometry makes the relationships predictable, not arbitrary.",
        "Think of the twelve branches as a clock face. Rat sits at midnight, Horse at noon — direct opposites, direct clash. Ox and Goat, Rabbit and Rooster, Dragon and Dog, Tiger and Monkey, Snake and Pig all work the same way. Meanwhile, the Three Harmonies triangles connect animals 120 degrees apart — the classic 'trine' from Western astrology has an equivalent here, rooted in the same seasonal logic."
      ]
    },
    {
      "h2": "The Three Harmonies (Sān Hé): Who Strengthens Whom",
      "paragraphs": [
        "The Three Harmonies group animals that share a dominant elemental phase across three seasons. They are not identical in temperament — that variety is actually the point. Each triangle has one animal that initiates the energy, one that peaks it, and one that consolidates it. Together they form a cycle that functions better than any single member alone.",
        "Rat (Water), Dragon (Earth with a Water reservoir), and Monkey (Metal, which generates Water) form the Water triangle. These three share a forward-moving, strategic quality. A Rat's sharp timing, a Dragon's executive presence, and a Monkey's quick problem-solving create a group that plans well and executes fast. In a business partnership or friendship, this trio rarely stagnates.",
        "Ox (Earth), Snake (Fire with an Earth component), and Rooster (Metal generated by Earth) form the Metal triangle. This group values precision, persistence, and quality. An Ox's long-term commitment steadies a Snake's private strategy and a Rooster's exacting standards. They are slow to warm up, but once aligned, they build things that last decades.",
        "Tiger (Wood), Horse (Fire generated by Wood), and Dog (Earth with a Fire reservoir) form the Fire triangle. These three are the most outwardly energetic grouping — brave, social, and driven by values. A Tiger's moral courage, a Horse's momentum, and a Dog's loyalty produce partnerships that feel principled and alive. They can burn through conflict together because they share a sense of justice.",
        "Rabbit (Wood), Goat (Earth with a Wood component), and Pig (Water, which feeds Wood) form the Wood triangle. This is the most relationship-oriented and creatively attuned group. A Rabbit's diplomacy, a Goat's warmth, and a Pig's generosity produce an environment where people feel genuinely seen. They may struggle with assertiveness, but together they create beauty and belonging."
      ],
      "pullQuote": "The Three Harmonies work because difference within a shared element creates balance — not because similar personalities attract."
    },
    {
      "h2": "The Six Clashes (Liù Chōng): Friction, Not Fate",
      "paragraphs": [
        "A clash between two animals means their Earthly Branch energies directly oppose each other. In practice, this can look like constant low-grade tension, power struggles, or an inability to settle into a shared rhythm. It does not mean the relationship is doomed — many successful couples and business partners clash on this axis. But it does mean both people will need to work harder at mutual understanding than harmonious pairs do.",
        "Rat and Horse clash. Rat is midnight, cautious, calculating; Horse is noon, instinctive, freedom-hungry. Rat wants a plan before moving. Horse wants to be moving before there is a plan. This is not an unsolvable difference, but it needs naming. Without awareness, these two will interpret each other's defaults as personal attacks.",
        "Ox and Goat clash. Both are Earth, but Ox is methodical and Goat is feeling-led. Ox reads Goat's emotionality as instability; Goat reads Ox's steadiness as coldness. In long-term partnerships, this can create a slow freeze where neither feels fully accepted.",
        "Tiger and Monkey clash. Tiger leads from principle; Monkey leads from cleverness. Tiger finds Monkey slippery; Monkey finds Tiger rigid. In a work setting, they can produce brilliant results through creative friction — but one of them usually burns out from the pace of conflict.",
        "Rabbit and Rooster clash. Rabbit softens; Rooster sharpens. Rabbit wants harmony preserved; Rooster wants truth stated. In close relationships, Rooster's bluntness can wound Rabbit badly, and Rabbit's conflict-avoidance can frustrate Rooster into escalation. Mutual respect for each other's communication style is the entire game here.",
        "Dragon and Dog clash. Both are Yang Earth, both are strong-willed. Dragon wants scale and ambition; Dog wants justice and loyalty. They often share values but argue bitterly about methods. This is the clash that looks like the most compatible pairing from the outside — and is the most exhausting from the inside.",
        "Snake and Pig clash. Snake is private, strategic, slow to trust; Pig is open, generous, trusting by default. Snake's guardedness reads as coldness to Pig; Pig's openness reads as naivety to Snake. In business this can work if roles are clearly defined, but in intimacy it requires steady, patient translation."
      ]
    },
    {
      "h2": "Why Your Year Animal Is Only the Beginning",
      "paragraphs": [
        "A BaZi chart has four pillars — Year, Month, Day, and Hour — and each pillar contains two characters: a Heavenly Stem and an Earthly Branch. The zodiac animal is the Earthly Branch of the Year Pillar. It shapes how the world first perceives you and how you navigated your family of origin. For surface-level social compatibility, it matters. For deep partnership compatibility, it is one data point among eight.",
        "The Day Pillar is where intimate relationships live. The Day Master (the Heavenly Stem of your Day Pillar) reveals your core nature — how you love, what depletes you, what you need to thrive. Two people with clashing Year animals but harmonious Day Masters often describe their relationship as surprisingly easy. Two people with harmonious Year animals but clashing Day elements often describe a relationship that looks good on paper but feels draining in practice.",
        "The Month Pillar governs career drive and values. The Hour Pillar governs your private world and how you parent or mentor. A thorough compatibility reading looks at all four pillars and how the eight characters interact — not just whether two animals appear on the same list. Use the zodiac layer as an introduction, not a conclusion."
      ],
      "pullQuote": "Two people with clashing Year animals but harmonious Day Masters often describe their relationship as surprisingly easy."
    },
    {
      "h2": "How to Use This in Real Life",
      "paragraphs": [
        "If you are in a Three Harmonies pairing — Rat-Dragon-Monkey, Ox-Snake-Rooster, Tiger-Horse-Dog, or Rabbit-Goat-Pig — lean into what the shared element does best. Water trios: build long-range plans together. Metal trios: create standards and workflows you both commit to. Fire trios: pursue something meaningful with a shared moral stake. Wood trios: make a home or a creative project that neither of you would have built alone.",
        "If you are in a Six Clashes pairing, the practical move is to name your defaults explicitly rather than assuming bad intent. Rat-Horse pairs should agree on a decision-making rhythm before a big choice arrives. Tiger-Monkey pairs should assign lanes — let one person own the 'why' and the other own the 'how.' Dragon-Dog pairs need a shared cause bigger than the relationship itself, or the value-disagreements fill all available space.",
        "Compatibility in any system — Chinese or otherwise — is less about finding someone frictionless and more about understanding where the friction lives so you can address it directly. BaZi gives you a map. What you do with that map is still entirely up to you. Run your full chart on the calculator to see all four pillars before drawing conclusions about any specific relationship."
      ]
    }
  ],
  "faqs": [
    {
      "q": "Are Six Clashes pairs always bad together?",
      "a": "No. A clash means effort is required, not that the relationship fails. Many long-term couples and business partners clash on the zodiac wheel. The difference is that they have learned to name their opposing defaults rather than personalizing them. Dragon-Dog couples who find a shared cause, or Rat-Horse pairs who negotiate decision-making styles, often build unusually resilient relationships precisely because they had to work things out consciously."
    },
    {
      "q": "What if my year animal is in a Three Harmonies group with someone, but we still struggle?",
      "a": "Year animal harmony is a surface indicator. Real friction often lives in the Day Pillar, the Month Pillar, or the interaction between specific Heavenly Stems. Two people in the same Three Harmonies triangle can still have clashing Day Masters that create daily wear. Look at the full BaZi chart. The year animal is a starting point, not a guarantee."
    },
    {
      "q": "Does this apply to friendships and work partnerships, not just romance?",
      "a": "Yes, and arguably it is even more useful there. Three Harmonies groupings describe energy compatibility, not romantic chemistry specifically. A Rat-Dragon-Monkey founding team, an Ox-Rooster quality-control pairing, or a Tiger-Dog activist duo all make structural sense through this lens. For work and friendship, the Year and Month pillars are more relevant than the Day Pillar, which is primarily the domain of intimate partnership."
    },
    {
      "q": "My partner and I have the same zodiac animal. Is that good or bad?",
      "a": "Same-animal pairings — called self-penalties (zì xíng 自刑) in some contexts — vary by animal. They are not automatically harmonious or conflicted. What happens is that each person amplifies the other's default tendencies, positive and shadow alike. Two Horses together bring enormous energy and almost no natural brake. Two Rabbits together create a very peaceful, possibly too-conflict-averse home. Know the animal's shadow side and check your Day Masters for balance."
    },
    {
      "q": "How do I find my actual Day Master for deeper compatibility work?",
      "a": "Your Day Master (rì zhǔ) is the Heavenly Stem of your Day Pillar — one of ten possible stems, each a Yin or Yang version of the five elements. You cannot calculate it from your birthday alone without a BaZi calculator, because it depends on the precise day of birth in the traditional Chinese calendar. Use the free calculator on this site to generate your full four-pillar chart and identify your Day Master."
    },
    {
      "q": "Can compatibility change over time with luck cycles?",
      "a": "Yes. BaZi includes ten-year luck cycles (dà yùn 大运) that layer new elemental energies over your natal chart. A pairing that feels tense in your twenties may ease significantly when both partners enter luck cycles that balance their charts. Conversely, a harmonious pairing can hit turbulence during a luck cycle that activates a hidden clash. Compatibility is not a fixed score — it is a dynamic between two evolving charts."
    }
  ],
  "related": [
    {
      "kind": "zodiac",
      "slug": "rat"
    },
    {
      "kind": "zodiac",
      "slug": "dragon"
    },
    {
      "kind": "article",
      "slug": "best-zodiac-matches"
    },
    {
      "kind": "article",
      "slug": "bazi-relationship-pillar"
    }
  ],
  "publishedAt": "2026-05-15",
  "readingMinutes": 9
};
