// Generated by scripts/generate-articles.ts — do not edit by hand.
import type { Article } from "../types";

export const article: Article = {
  "slug": "dominant-element-bazi",
  "title": "How to Know Your Dominant Element From Your BaZi Chart",
  "h1": "How to Know Your Dominant Element From Your BaZi Chart",
  "metaDescription": "Your dominant element is the one that shapes how you move through the world. Here's a 3-step method to find it from your BaZi chart, no calculator needed.",
  "primaryKeyword": "dominant element bazi",
  "category": "elements",
  "tldr": "Count each element across your chart's eight characters, weight the month branch most heavily, then check whether your Day Master sits inside or outside the dominant group. The element that scores highest — adjusted for position — is your dominant element.",
  "intro": [
    "Your BaZi chart (八字, bā zì, literally 'eight characters') holds four pillars — Hour, Day, Month, and Year. Each pillar has a top character called a Heavenly Stem (tiān gān 天干) and a bottom character called an Earthly Branch (dì zhī 地支). Together those eight characters carry Wood, Fire, Earth, Metal, or Water energy. The element that shows up most — especially in the positions that carry the most weight — is your dominant element.",
    "Finding it matters because your dominant element shapes your default mode: how you start projects, what stresses you out, how you relate to money, where your health tends to buckle. This guide gives you a three-step method you can apply to any printed chart. You will need your chart in front of you — run it free at the calculator link below if you don't have it yet."
  ],
  "sections": [
    {
      "h2": "What 'Dominant Element' Actually Means",
      "paragraphs": [
        "In BaZi theory, every one of the ten Heavenly Stems maps to a specific element and polarity — Yang Wood (Jiǎ 甲), Yin Wood (Yǐ 乙), Yang Fire (Bǐng 丙), and so on. Every one of the twelve Earthly Branches also carries a primary element, plus hidden elements stored inside it. When one element appears frequently across those eight characters, and especially in high-weight positions, it dominates the chart's energy landscape.",
        "Dominant does not mean 'best' or 'worst.' A chart heavy in Metal belongs to someone who is naturally precise, decisive, and high-standard — and who also risks rigidity and emotional coldness when that Metal has no balancing element. Knowing which element dominates helps you understand your default behaviors and where targeted adjustments pay off most."
      ]
    },
    {
      "h2": "Step 1 — Count Every Stem and Branch by Element",
      "paragraphs": [
        "Write out your eight characters and assign each one its primary element. For Heavenly Stems this is direct: Jiǎ (甲) and Yǐ (乙) = Wood; Bǐng (丙) and Dīng (丁) = Fire; Wù (戊) and Jǐ (己) = Earth; Gēng (庚) and Xīn (辛) = Metal; Rén (壬) and Guǐ (癸) = Water. For Earthly Branches, use the primary element only for now: Zi (子) = Water; Chǒu (丑) = Earth; Yín (寅) = Wood; Mǎo (卯) = Wood; Chén (辰) = Earth; Sì (巳) = Fire; Wǔ (午) = Fire; Wèi (未) = Earth; Shēn (申) = Metal; Yǒu (酉) = Metal; Xū (戌) = Earth; Hài (亥) = Water.",
        "Tally your five columns — Wood, Fire, Earth, Metal, Water. This raw count is your starting point. A sample raw result might look like: Wood 3, Fire 1, Earth 2, Metal 1, Water 1. Don't stop here. Counts alone miss the fact that not all eight characters carry equal influence."
      ],
      "list": {
        "type": "bullet",
        "items": [
          "Wood stems: Jiǎ (甲), Yǐ (乙) — branches: Yín (寅), Mǎo (卯)",
          "Fire stems: Bǐng (丙), Dīng (丁) — branches: Sì (巳), Wǔ (午)",
          "Earth stems: Wù (戊), Jǐ (己) — branches: Chǒu (丑), Chén (辰), Wèi (未), Xū (戌)",
          "Metal stems: Gēng (庚), Xīn (辛) — branches: Shēn (申), Yǒu (酉)",
          "Water stems: Rén (壬), Guǐ (癸) — branches: Zi (子), Hài (亥)"
        ]
      }
    },
    {
      "h2": "Step 2 — Weight by Position",
      "paragraphs": [
        "In BaZi, the Month Pillar carries the most seasonal and elemental force — it sets the climate the whole chart breathes in. Assign it a weight of 3. The Day Branch (the animal sign directly under your Day Master) is your personal root and carries a weight of 2. All other branches and all four stems get a weight of 1 each.",
        "Go back to your tally and multiply each character's element score by its position weight. Month Branch × 3, Day Branch × 2, everything else × 1. Sum each element column again with the weighted values. In the sample above, if the three Wood characters included the Month Branch (Yín, weight 3) and the Day Branch (Mǎo, weight 2), Wood's weighted score jumps to 3 + 2 + 1 = 6, while Earth's two characters at weight 1 each stay at 2. Wood now leads clearly.",
        "This weighting reflects classical BaZi reasoning: the season you were born in — captured by the Month Branch — floods the chart with its energy the way summer heat floods a house even when the windows are closed. A single Metal character in the Month Branch can outweigh three Metal characters scattered across lower-weight positions."
      ],
      "pullQuote": "The season you were born in floods the chart like summer heat floods a house — even when the windows are closed."
    },
    {
      "h2": "Step 3 — Cross-Check With Your Day Master",
      "paragraphs": [
        "Your Day Master (rì zhǔ 日主) is the Heavenly Stem of the Day Pillar — it represents you at the core. Identifying whether your Day Master belongs to the same element as the chart's dominant element tells you whether you are a 'strong' or 'weak' Day Master, which changes how that dominant element behaves.",
        "If your Day Master shares the dominant element — say you are Yang Wood Jiǎ and Wood leads the chart — you have a strong Day Master in a Wood-dominant chart. The pioneering, growth-oriented energy of Wood is both what the chart pushes and what you are. Expect confidence, momentum, and a stubbornness that occasionally tips into rigidity.",
        "If your Day Master differs — say you are Yang Fire Bǐng but Earth dominates the chart — the dominant element is something outside you. Earth is the environment pressing on you, not the core of your identity. You may find yourself constantly playing support roles, or drawn to stability-oriented fields, even though your personal nature is expressive and outward-facing. The gap between Day Master and dominant element is often where interesting tension lives."
      ]
    },
    {
      "h2": "Sample Chart Walk-Through",
      "paragraphs": [
        "Take a person born in early spring, whose chart reads: Year Stem Jiǎ (Wood), Year Branch Zi (Water); Month Stem Bǐng (Fire), Month Branch Yín (Wood); Day Stem Bǐng (Fire), Day Branch Wǔ (Fire); Hour Stem Jiǎ (Wood), Hour Branch Mǎo (Wood). Raw count: Wood 4 (Jiǎ × 2, Yín, Mǎo), Fire 3 (Bǐng × 2, Wǔ), Water 1 (Zi). Earth and Metal = 0.",
        "Now apply position weights. Month Branch Yín = Wood × 3. Day Branch Wǔ = Fire × 2. All others × 1. Weighted Wood: Jiǎ (year stem) 1 + Zi... wait, Zi is Water — scratch that. Weighted Wood: Year Stem Jiǎ = 1, Month Stem Bǐng... that's Fire. Let's be precise: Wood characters are Year Stem Jiǎ (1), Month Branch Yín (3), Hour Stem Jiǎ (1), Hour Branch Mǎo (1). Total Wood = 6. Fire characters are Month Stem Bǐng (1), Day Stem Bǐng (1), Day Branch Wǔ (2). Total Fire = 4. Water: Year Branch Zi (1). Total Water = 1.",
        "Wood dominates at 6. The Day Master is Yang Fire Bǐng — a Fire type in a Wood-dominant chart. Wood feeds Fire in the generative cycle (mù shēng huǒ 木生火), so the environment continuously fuels this person's natural expressiveness. They likely have strong creative drive, easy access to inspiration, and a tendency to burn through energy fast. The growth edge: add Earth and Metal habits (structure, deadlines, editing) to convert all that generative momentum into finished work."
      ]
    },
    {
      "h2": "When the Count Is a Tie",
      "paragraphs": [
        "Sometimes two elements score within one point of each other after weighting. In that case, look first at whether either element includes the Month Branch — whichever element holds the Month Branch wins the tiebreaker. If neither does, look at the Day Branch. If that's still a tie, the element that matches your Day Master is the operative dominant element, because it describes you and the chart's environment simultaneously.",
        "A near-tie also carries its own meaning: the chart is relatively balanced between two elements, and that person often displays a blended personality. A close Wood-Water tie produces someone who is simultaneously visionary (Wood) and deeply intuitive (Water) — the novelist who can actually build the platform to publish. True balance across all five elements is rare and worth noting separately."
      ]
    },
    {
      "h2": "What to Do With This Information",
      "paragraphs": [
        "Once you know your dominant element, read its profile with fresh eyes. If Fire dominates, your natural strengths are visibility, communication, and warmth — and your shadow risks are burnout, scattered attention, and scorching people with too much directness. The balancing elements (Water to cool, Earth to contain) point directly at practical lifestyle adjustments: more sleep, more structure, fewer commitments per quarter.",
        "Dominant element also shapes career fit in concrete ways. A Metal-dominant chart gravitates toward roles that reward precision and high standards — editing, surgery, law, quality assurance, financial audit. A Water-dominant chart tends toward strategy, research, long-horizon investing, and roles where patience is a competitive advantage. These are patterns, not constraints. Knowing the pattern is the first step to working with it deliberately rather than being run by it invisibly."
      ]
    }
  ],
  "faqs": [
    {
      "q": "Do hidden elements inside Earthly Branches count toward the dominant element?",
      "a": "In a full classical analysis, yes — every branch contains hidden stems (cáng gān 藏干) that add elemental weight. For a first-pass dominant element reading, using only the primary branch element is accurate enough and far simpler. If your result feels off, check the hidden stems of your Month and Day branches; they sometimes tip a near-tie."
    },
    {
      "q": "Can my dominant element change over time?",
      "a": "Your natal chart is fixed, but ten-year luck cycles (dà yùn 大运) and annual branches layer new elemental energy onto it. A person with a Water-dominant natal chart can move through a decade-long Fire cycle that temporarily makes Fire the operative dominant energy. This is why BaZi practitioners look at the natal chart and the current luck cycle together rather than in isolation."
    },
    {
      "q": "What if my Day Master is the only character of its element?",
      "a": "That is a weak Day Master — the chart's environment is dominated by something other than you. A lone Yang Fire Day Master in a Metal-heavy chart describes someone who feels like a candle in a cold metal room: expressive and warm by nature, but constantly up against environments that demand precision and restraint. Understanding the gap often explains why someone feels they are always swimming against the current."
    },
    {
      "q": "Is the dominant element the same as the favorable element (yòng shén 用神)?",
      "a": "Not necessarily. The dominant element describes what is most present. The favorable element (yòng shén) is what the chart needs — often the element that balances or controls the dominant one. If Fire dominates, Water or Earth are typically favorable. Dominant describes the reality; favorable describes the medicine. Both matter, but they are different questions."
    },
    {
      "q": "My chart has a lot of Earth Branches — is Earth always dominant?",
      "a": "Earth branches (Chǒu, Chén, Wèi, Xū) are the most common in the Earthly Branch cycle because they appear as transitional months between seasons. Many charts naturally accumulate Earth count. Run the position weighting carefully — if none of those Earth branches fall in the Month or Day position, a single Wood or Metal character in the Month Branch can still outweigh three Earth branches scattered elsewhere."
    },
    {
      "q": "Does the dominant element affect health patterns?",
      "a": "Traditional Chinese medicine (TCM) maps each element to organ systems: Wood to liver and gallbladder, Fire to heart and small intestine, Earth to spleen and stomach, Metal to lungs and large intestine, Water to kidneys and bladder. A dominant element under sustained stress — especially if its controlling element is also strong — is thought to correspond with vulnerability in those organ systems. BaZi does not diagnose illness, but the patterns are worth cross-referencing with a qualified TCM practitioner."
    }
  ],
  "related": [
    {
      "kind": "calculator"
    },
    {
      "kind": "article",
      "slug": "five-elements-explained"
    },
    {
      "kind": "article",
      "slug": "strong-vs-weak-day-master"
    },
    {
      "kind": "article",
      "slug": "missing-element-bazi"
    }
  ],
  "publishedAt": "2026-05-15",
  "readingMinutes": 9
};
