// Generated by scripts/generate-articles.ts — do not edit by hand.
import type { Article } from "../types";

export const article: Article = {
  "slug": "five-elements-explained",
  "title": "The Five Elements (Wu Xing) in BaZi: A Simple Guide",
  "metaDescription": "Wood, Fire, Earth, Metal, Water — the five forces behind every BaZi chart. Learn what each one means, what they look like in real life, and how they shape your reading.",
  "h1": "The Five Elements (Wu Xing 五行) — A Simple Guide to BaZi's Foundation",
  "category": "elements",
  "primaryKeyword": "five elements bazi",
  "tldr": "BaZi uses five elements — Wood, Fire, Earth, Metal, Water — as a framework for describing energy, personality, and timing. Each element appears in your chart as a Heavenly Stem or Earthly Branch. Their balance, excess, or absence shapes how you think, work, and relate to others.",
  "intro": [
    "Every BaZi chart is built from the same five building blocks: Wood (Mù 木), Fire (Huǒ 火), Earth (Tǔ 土), Metal (Jīn 金), and Water (Shuǐ 水). Together, they make up what classical Chinese philosophy calls Wu Xing (wǔ xíng 五行) — literally 'five movements' or 'five phases.' They are not static symbols. They are descriptions of how energy moves.",
    "Think of each element as a verb disguised as a noun. Wood expands. Fire expresses. Earth stabilizes. Metal refines. Water flows. When you read a BaZi chart, you are really asking: which movements does this person carry most naturally — and which ones are missing or blocked?"
  ],
  "sections": [
    {
      "h2": "Wood (Mù 木) — The Expanding Force",
      "paragraphs": [
        "Wood is the smell of soil after rain, the tension in a seed just before it cracks. It is the energy of beginnings — upward, forward, toward light. In spring, the earth breaks open not because it is forced but because Wood energy has nowhere else to go.",
        "In a person, strong Wood looks like someone who starts projects before they have permission, holds a moral position even when the room disagrees, and always seems to be building toward a horizon others can't see yet. Weak Wood looks like brilliant ideas that sit untouched in notebooks.",
        "Wood generates Fire and is controlled by Metal. The pioneer who plants the seed — that is Wood."
      ]
    },
    {
      "h2": "Fire (Huǒ 火) — The Expressive Force",
      "paragraphs": [
        "Fire is the noon sun through glass, the open laugh at a loud table, the moment a speaker finds the room. It illuminates — and what it illuminates, it shows plainly. Fire cannot whisper. It either burns or it doesn't.",
        "In a person, strong Fire is the colleague everyone wants at the pitch meeting, the friend who makes strangers feel instantly known. Weak Fire is the brilliant thinker who over-edits every sentence into silence, the warm person who has forgotten how to be seen.",
        "Fire generates Earth and is controlled by Water. The beacon that warms the room — that is Fire."
      ]
    },
    {
      "h2": "Earth (Tǔ 土) — The Stabilizing Force",
      "paragraphs": [
        "Earth is the pause between seasons — late summer when the year exhales. It is the dense, quiet center that everything else needs to push against. Touch it and it holds. Pour water on it and it absorbs without complaint.",
        "In a person, strong Earth is the team member no one can imagine leaving — the one who shows up with food when you're sick, who remembers every birthday, who finishes what was abandoned. Weak Earth is constant low-grade anxiety, skipped meals, and a habit of giving away more than gets returned.",
        "Earth generates Metal and is controlled by Wood. The ground that holds everything else steady — that is Earth."
      ]
    },
    {
      "h2": "Metal (Jīn 金) — The Refining Force",
      "paragraphs": [
        "Metal is the sharp edge of a well-made knife, the clean line of a sentence that lost all its fat, the silence after a decision has been made. It is the energy of reduction — removing what doesn't belong so what remains is true.",
        "In a person, strong Metal is the editor who finds the buried argument in a messy draft, the surgeon who makes exactly the right cut, the person who asks the uncomfortable question everyone else avoided. Weak Metal is endless revision, drawers full of unfinished things, grief that never quite moves through.",
        "Metal generates Water and is controlled by Fire. The blade that cuts cleanly when others negotiate — that is Metal."
      ]
    },
    {
      "h2": "Water (Shuǐ 水) — The Flowing Force",
      "paragraphs": [
        "Water is the deep lake in winter, still and cold on the surface, full of movement underneath. It is the energy of depth, intuition, and long patience. It does not push through obstacles — it finds the path that already exists, or wears one over years.",
        "In a person, strong Water is the strategist who maps out futures three moves ahead, the therapist who sits in silence until the right word surfaces. Weak Water is anxious decisions made before the picture is clear, a gut instinct that exists but goes unheard.",
        "Water generates Wood and is controlled by Earth. The river that finds every path — that is Water."
      ]
    },
    {
      "h2": "How the Five Elements Interact: Two Cycles",
      "paragraphs": [
        "Knowing each element alone is only half the picture. What gives BaZi its depth is the way elements interact. There are two main cycles to understand: the generating cycle (shēng 生), where each element feeds the next — Wood feeds Fire, Fire feeds Earth, Earth feeds Metal, Metal feeds Water, Water feeds Wood — and the controlling cycle (kè 克), where each element keeps another in check.",
        "These cycles explain why a chart with too much of one element creates problems, and why a chart that looks 'balanced' on paper can still feel stuck. The elements are in constant relationship. A single element in isolation tells you very little; the story lives in the dynamics between them.",
        "For a full explanation of how these two cycles work inside a real chart — and what it means when one element is feeding or attacking your Day Master (rì zhǔ 日主, the stem of your birth day) — see the dedicated guide to the generating and controlling cycles."
      ],
      "pullQuote": "The elements are not symbols. They are descriptions of how energy moves — and every chart is a map of which movements come naturally to you."
    }
  ],
  "faqs": [
    {
      "q": "Are the five elements the same as the Western four elements — earth, air, fire, water?",
      "a": "No, though the overlap in names can confuse things. The Chinese five elements are not substances — they are phases of movement. Wood is not a tree; it is the energy of expansion. Metal is not iron ore; it is the energy of refinement and reduction. The Western four-element system comes from Greek philosophy and carries different meanings. In BaZi, the five phases are functional: they describe what energy does, not what matter is made of."
    },
    {
      "q": "How do I find which elements are in my BaZi chart?",
      "a": "Your BaZi chart has eight characters — four Heavenly Stems (tiān gān 天干) and four Earthly Branches (dì zhī 地支) arranged in four Pillars for your birth year, month, day, and hour. Each character corresponds to an element. The free calculator at fivebazi.com shows you all eight characters and their elements instantly, so you can see at a glance which elements dominate and which are absent."
    },
    {
      "q": "What does it mean if I have no Water in my chart?",
      "a": "Missing an element doesn't mean you lack that quality entirely — it means the energy comes less naturally and may require more conscious effort. Someone with no Water might find it harder to slow down before deciding, to trust intuition, or to sit comfortably in uncertainty. They often compensate by over-researching. The controlling and generating cycles also matter: strong Metal in a chart generates Water indirectly, softening the absence."
    },
    {
      "q": "Can I change my elements through lifestyle choices?",
      "a": "BaZi doesn't change — your birth data is fixed. But the tradition has always included practical advice about environments, routines, and relationships that support weaker elements. Someone low in Earth might stabilize through regular meal times and consistent physical routines. Someone low in Fire might benefit from more performance, public speaking, or even just dressing in warmer colors. These aren't magic fixes; they're small environmental inputs that make natural patterns easier to access."
    },
    {
      "q": "Which element is the most powerful or important?",
      "a": "None. The framework is explicitly about balance and relationship, not hierarchy. Fire is not superior to Water; each controls and generates others in turn. In any given chart, the 'most important' element is the one your Day Master needs most — the one that supports, balances, or unlocks your core energy. That answer is different for every person."
    },
    {
      "q": "Do the five elements change with the year, or are they fixed in my chart?",
      "a": "Both. Your birth chart is fixed — those eight characters don't change. But BaZi also maps time: each year, month, and ten-year luck period carries its own elemental energy that interacts with your fixed chart. A Water-heavy year might feel energizing to someone with weak Water and overwhelming to someone who already has too much. This dynamic between fixed chart and moving time is where most practical BaZi analysis lives."
    }
  ],
  "related": [
    {
      "kind": "element",
      "slug": "wood"
    },
    {
      "kind": "element",
      "slug": "fire"
    },
    {
      "kind": "element",
      "slug": "earth"
    },
    {
      "kind": "element",
      "slug": "metal"
    },
    {
      "kind": "element",
      "slug": "water"
    },
    {
      "kind": "article",
      "slug": "generative-controlling-cycle"
    }
  ],
  "publishedAt": "2026-05-15",
  "readingMinutes": 6
};
