// Generated by scripts/generate-articles.ts — do not edit by hand.
import type { Article } from "../types";

export const article: Article = {
  "slug": "zodiac-year-boundary",
  "title": "When Does a Chinese Zodiac Year Actually Start?",
  "h1": "When Does a Chinese Zodiac Year Actually Start? (Hint: Not January 1)",
  "metaDescription": "If your birthday is in January or early February, you may belong to a different Chinese zodiac than you thought. Here's the real start of each lunar year — and the solar one BaZi uses.",
  "primaryKeyword": "when does chinese new year start zodiac",
  "category": "zodiac",
  "tldr": "Chinese New Year (Lunar New Year) falls between late January and mid-February and is what most calendar apps use for zodiac signs. BaZi (Four Pillars of Destiny) uses a different boundary: Lìchūn (立春), the solar term that falls around February 3–5. If your birthday sits between January 1 and roughly February 5, your zodiac sign may differ depending on which system you use — and BaZi's answer is usually the one that matters for chart readings.",
  "intro": [
    "Every January, millions of people born in late January or early February quietly wonder which zodiac animal they belong to. The calendar says one year; the lunar calendar says another. Both answers can be correct — they're just answers to different questions.",
    "There are two legitimate start-points for the Chinese zodiac year. The first is Lunar New Year, the festival most people recognize — a moving date tied to the moon, falling anywhere from January 21 to February 20. The second is Lìchūn (立春, 'Start of Spring'), a solar term fixed to the sun's position at roughly February 3–5 each year. BaZi, the classical Chinese destiny system, uses Lìchūn as its year boundary, not the moon.",
    "Getting this wrong means your entire chart shifts. One zodiac sign, one set of branch interactions, one completely different reading. If your birthday sits in the first five weeks of the calendar year, keep reading."
  ],
  "sections": [
    {
      "h2": "Why There Are Two Different Start Dates",
      "paragraphs": [
        "The Chinese calendar is actually two calendars running in parallel. The lunar calendar — the one that governs Lunar New Year (Chūnjié, 春节), festivals, and the public-facing zodiac — tracks moon cycles. Because lunar months don't divide evenly into a solar year, New Year drifts across a five-week window. In 2023 it fell on January 22. In 2015 it fell on February 19. That's nearly a full month of variation.",
        "BaZi uses the solar calendar (gān zhī, 干支 — the Stems and Branches calendar), which fixes the year's start to Lìchūn, the moment the sun reaches 315 degrees ecliptic longitude. This happens around February 3, 4, or 5 every year — the same narrow window, year after year. For chart calculation purposes, Lìchūn is the only boundary that matters."
      ]
    },
    {
      "h2": "What Lìchūn Actually Is",
      "paragraphs": [
        "Lìchūn (立春) translates literally as 'Standing Spring' or 'Start of Spring.' It is one of 24 solar terms (jiéqì, 节气) that divide the solar year into equal segments of 15 degrees each. These terms governed farming, medicine, and classical divination long before the festival calendar took cultural center stage.",
        "In practical terms, Lìchūn falls on February 3 in some years, February 4 in most, and February 5 occasionally — determined by the sun's exact position, not a committee decision. BaZi practitioners calculate the precise time down to the hour, because a child born at 11 pm on February 3 and another born at 3 am on February 4 can fall in different zodiac years depending on the year in question. For most people, the exact Lìchūn time is available in any reputable Chinese almanac or astrology calculator."
      ],
      "pullQuote": "Lìchūn is fixed to the sun, not the moon. It falls in a three-day window every year — and it is the true year boundary in BaZi."
    },
    {
      "h2": "The Lunar New Year Boundary: What It Gets Right (and Wrong)",
      "paragraphs": [
        "Lunar New Year is not wrong as a cultural marker — it is exactly what it claims to be: the first day of the first lunar month. For festivals, red envelopes, and family reunions, this is the correct date. Most zodiac calendars sold in shops, printed on restaurant placemats, and cited in newspaper horoscopes use this boundary. If you were born on February 10, 2002, those sources will tell you you're a Horse.",
        "The problem is that classical Chinese astrology — including BaZi, Zi Wei Dou Shu (紫微斗数), and traditional almanac readings — was never built on the lunar calendar alone. It was built on the solar Stems-and-Branches system. Using Lunar New Year as the zodiac boundary for a BaZi reading is like using a weather app set to the wrong city: it looks right but the forecast is off. The further your birthday is from mid-February, the less it matters. But if you're in that five-week window, the difference is a completely different animal."
      ]
    },
    {
      "h2": "Borderline Years: Lunar New Year vs. Lìchūn",
      "paragraphs": [
        "The following list covers recent years where the gap between Lunar New Year and Lìchūn is wide enough to matter. If your birthday falls between the two dates shown, the popular zodiac calendar gives you one animal while BaZi gives you another.",
        "Use the right column (Lìchūn date) if you are doing a BaZi reading. Use the left column (Lunar New Year date) if you are consulting a festival calendar or a general zodiac reference."
      ],
      "list": {
        "type": "bullet",
        "items": [
          "2000: Lunar New Year Feb 5 (Dragon starts) · Lìchūn Feb 4 — born Feb 4 before exact Lìchūn time = Rabbit in BaZi",
          "2001: Lunar New Year Jan 24 (Snake starts) · Lìchūn Feb 4 — born Jan 24–Feb 3 = Dragon in BaZi, Snake on popular calendars",
          "2004: Lunar New Year Jan 22 (Monkey starts) · Lìchūn Feb 4 — born Jan 22–Feb 3 = Goat in BaZi",
          "2007: Lunar New Year Feb 18 (Pig starts) · Lìchūn Feb 4 — born Feb 4–17 = Pig in BaZi, Dog on popular calendars",
          "2012: Lunar New Year Jan 23 (Dragon starts) · Lìchūn Feb 4 — born Jan 23–Feb 3 = Rabbit in BaZi",
          "2015: Lunar New Year Feb 19 (Goat starts) · Lìchūn Feb 4 — born Feb 4–18 = Goat in BaZi, Horse on popular calendars",
          "2017: Lunar New Year Jan 28 (Rooster starts) · Lìchūn Feb 3 — born Jan 28–Feb 2 = Monkey in BaZi",
          "2019: Lunar New Year Feb 5 (Pig starts) · Lìchūn Feb 4 — born Feb 4 before exact time = Dog in BaZi",
          "2022: Lunar New Year Feb 1 (Tiger starts) · Lìchūn Feb 4 — born Feb 1–3 = Ox in BaZi, Tiger on popular calendars",
          "2023: Lunar New Year Jan 22 (Rabbit starts) · Lìchūn Feb 4 — born Jan 22–Feb 3 = Tiger in BaZi"
        ]
      }
    },
    {
      "h2": "How to Know Which Answer to Use",
      "paragraphs": [
        "For casual purposes — choosing a zodiac phone case, reading a Lunar New Year horoscope column, or explaining your sign at a dinner party — the Lunar New Year boundary is fine. No one at the table needs the solar term correction.",
        "For any serious BaZi reading — career timing, relationship compatibility analysis, the Ten-Year Luck Pillars (dà yùn, 大运) — use Lìchūn. Run your birth date and time through a BaZi calculator that specifies it uses the solar Stems-and-Branches system. The exact time of Lìchūn shifts by a few hours each year, so if your birthday is February 3, 4, or 5, you will want the calculator to show you the precise transition time, not just the date.",
        "The simplest rule: if your birthday is January 1 through January 20 in any year, your BaZi zodiac is always the previous year's animal — Lunar New Year has never fallen before January 21. If your birthday is January 21 through February 5, check both dates against the specific year. If your birthday is February 6 or later, all systems agree: you are the new year's animal."
      ],
      "pullQuote": "January 1 through January 20: always the previous year's animal in BaZi. February 6 onward: all systems agree. The gap that matters is January 21 to February 5."
    },
    {
      "h2": "Does the Zodiac Animal Change Your Entire BaZi Chart?",
      "paragraphs": [
        "The zodiac sign most people discuss corresponds to the Year Pillar (nián zhù, 年柱) in BaZi — one of four pillars that also include the Month, Day, and Hour. Getting the Year Pillar wrong is meaningful but not the whole story. The Day Master (rì zhǔ, 日主) — derived from the Day Pillar — is considered the most personally significant pillar, and its calculation is not affected by the Lìchūn question at all.",
        "Where the Year Pillar correction matters most is in compatibility readings (which examine how the year branch interacts with other branches), in calculating your Ten-Year Luck Pillars, and in any reading that focuses on your childhood or ancestral circumstances, which the Year Pillar traditionally represents. If you have been getting readings that never quite fit and you were born in late January or early February, this is the first thing to check."
      ]
    }
  ],
  "faqs": [
    {
      "q": "Is Chinese New Year always on February 4?",
      "a": "No — Lunar New Year (Chinese New Year) moves each year based on the moon, landing anywhere from January 21 to February 20. February 4 is approximately when Lìchūn (立春) falls, which is a different date entirely. Lìchūn is the solar start of spring used in BaZi; it stays within a three-day window (Feb 3–5) because it is calculated from the sun's position, not the moon's."
    },
    {
      "q": "I was born on February 2, 2002. Am I a Horse or a Snake in BaZi?",
      "a": "In 2002, Lunar New Year (Horse year) began on February 12, and Lìchūn fell on February 4. Your birthday is February 2, which is before both dates. That means in BaZi you are a Snake (the 2001 animal), even though the year 2002 is commonly called the Year of the Horse. Popular zodiac calendars would also call you a Snake for the same reason — here both systems agree."
    },
    {
      "q": "Why do some online zodiac calculators give different answers for borderline birthdays?",
      "a": "Most general zodiac apps and websites use Lunar New Year as the cutoff. BaZi-specific calculators use Lìchūn. Both are internally consistent — they just answer different questions. If a calculator does not tell you which boundary it uses, assume it is Lunar New Year. For an accurate BaZi reading, use a calculator that explicitly applies the solar Stems-and-Branches calendar with Lìchūn as the year boundary."
    },
    {
      "q": "Does the exact time of Lìchūn matter, or just the date?",
      "a": "The exact time matters if your birthday is on February 3, 4, or 5. Lìchūn shifts by a few hours from year to year — in some years it occurs at 6 am, in others at 11 pm. A person born on February 4 at 2 am and another born the same day at 8 pm could technically fall in different zodiac years. Any serious BaZi calculator will account for this and show you the precise transition time."
    },
    {
      "q": "If I correct my zodiac year using Lìchūn, do I need to redo my entire BaZi chart?",
      "a": "Only the Year Pillar changes — the Month, Day, and Hour Pillars are unaffected. That said, the Year Pillar feeds into compatibility readings, Ten-Year Luck Pillar calculations, and interpretations of early life circumstances, so it is worth correcting before any serious reading. Your Day Master, which most practitioners consider the core of the chart, stays exactly the same regardless of which year boundary you use."
    },
    {
      "q": "Which system should I use for Chinese zodiac compatibility readings?",
      "a": "If the compatibility reading is purely cultural or social — the kind found in Lunar New Year supplements and gift books — the Lunar New Year boundary is fine. If you are doing a BaZi-based compatibility reading that examines how your Four Pillars interact with another person's, use Lìchūn for both birthdays. The branch interactions that drive compatibility analysis are part of the solar Stems-and-Branches system, so mixing calendars will produce unreliable results."
    }
  ],
  "related": [
    {
      "kind": "article",
      "slug": "solar-vs-lunar-calendar-bazi"
    },
    {
      "kind": "article",
      "slug": "chinese-zodiac-compatibility"
    },
    {
      "kind": "zodiac",
      "slug": "rat"
    },
    {
      "kind": "calculator"
    }
  ],
  "publishedAt": "2026-05-15",
  "readingMinutes": 8
};
