"use client";

import { useState } from "react";
import type { BaZiChart } from "@/lib/bazi";

interface Props {
  chart: BaZiChart;
  name: string;
}

type Status = "idle" | "streaming" | "done" | "error";

export default function AIReading({ chart, name }: Props) {
  const [text, setText] = useState("");
  const [status, setStatus] = useState<Status>("idle");
  const [error, setError] = useState<string | null>(null);

  async function generate() {
    setStatus("streaming");
    setText("");
    setError(null);

    try {
      const response = await fetch("/api/reading", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          name,
          year: chart.birth.year,
          month: chart.birth.month,
          day: chart.birth.day,
          hour: chart.birth.hour,
          minute: chart.birth.minute,
          isMale: chart.isMale,
        }),
      });

      if (!response.ok || !response.body) {
        throw new Error(`HTTP ${response.status}`);
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        setText(buffer);
      }
      setStatus("done");
    } catch (err) {
      console.error(err);
      setError(err instanceof Error ? err.message : "Reading failed");
      setStatus("error");
    }
  }

  if (status === "idle") {
    return (
      <div className="mx-auto max-w-2xl rounded-3xl border border-line bg-paper p-8 text-center sm:p-10">
        <p className="text-xs font-medium uppercase tracking-[0.35em] text-gold">
          ✦ AI Reading ✦
        </p>
        <h2 className="mt-3 font-serif text-3xl font-medium text-ink sm:text-4xl">
          Read your chart in plain English
        </h2>
        <p className="mx-auto mt-3 max-w-md text-ink-soft">
          A personalized 800-word reading written specifically for{" "}
          <span className="font-medium text-ink">{name || "you"}</span> — your
          essence, your strengths, your shadow side, and what your chart is
          asking you to do next.
        </p>
        <button
          onClick={generate}
          className="mt-6 inline-flex items-center gap-2 rounded-xl bg-ink px-6 py-3.5 font-serif text-base text-cream shadow-sm transition hover:bg-teal-soft"
        >
          Generate My Reading
          <span aria-hidden>→</span>
        </button>
        <p className="mt-3 text-xs text-ink-soft">
          ✦ Free · Takes about 15 seconds ✦
        </p>
      </div>
    );
  }

  return (
    <div className="mx-auto max-w-2xl">
      <header className="text-center">
        <p className="text-xs font-medium uppercase tracking-[0.35em] text-gold">
          Your Reading
        </p>
        <h2 className="mt-3 font-serif text-3xl font-medium text-ink sm:text-4xl">
          For {name || "You"}
        </h2>
      </header>

      <article className="mt-8 space-y-6">
        {renderReading(text)}
        {status === "streaming" && (
          <span
            className="inline-block h-4 w-1.5 animate-pulse bg-ink align-middle"
            aria-hidden
          />
        )}
      </article>

      {status === "error" && (
        <div className="mt-6 rounded-xl border border-line bg-cream-soft p-4 text-sm text-ink-soft">
          Something went wrong: {error}.{" "}
          <button
            onClick={generate}
            className="underline hover:text-ink"
          >
            Try again
          </button>
          .
        </div>
      )}

      {status === "done" && (
        <p className="mt-8 text-center text-xs text-ink-soft">
          ✦ Reading generated by Claude · For educational purposes only ✦
        </p>
      )}
    </div>
  );
}

/** Lightweight markdown renderer for `## Heading` + paragraphs. */
function renderReading(markdown: string) {
  if (!markdown.trim()) return null;

  // Split on `## ` at line start. The first fragment may be empty if the
  // text starts directly with `## `; filter it out.
  const sections = markdown.split(/^## /m).filter((s) => s.trim());

  return sections.map((section, i) => {
    const newlineIdx = section.indexOf("\n");
    const heading = newlineIdx === -1 ? section.trim() : section.slice(0, newlineIdx).trim();
    const body = newlineIdx === -1 ? "" : section.slice(newlineIdx + 1).trim();

    return (
      <section key={i} className="space-y-3">
        <h3 className="font-serif text-2xl text-ink">{heading}</h3>
        {body.split(/\n\n+/).map((paragraph, j) => (
          <p
            key={j}
            className="text-base leading-relaxed text-ink-soft"
          >
            {paragraph}
          </p>
        ))}
      </section>
    );
  });
}
